
services:
  app:
    build: .
    ports:
      - 127.0.0.1:8080:8080

    depends_on:
      - mysql
    volumes:
      - ./:/webapp
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=nbs
    tty: true
    stdin_open: true
  mysql:
    image: mysql:8.0
    volumes:
      - webapp-mysql-data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_DATABASE=nbs
      - MYSQL_ROOT_PASSWORD=root
      
volumes:
  webapp-mysql-data:
    